### PR TITLE
 Displays Preservation Event Notification on Work Page #1027.

### PR DESCRIPTION
**Pull request by bwatson78**
- app/assets/stylesheets/curate.scss: colors the two different type of notification.
- curate_generic_work_indexer.rb: adds logic to deliver the right info to the solr field.
- app/models/solr_document.rb and curate_generic_work_presenter.rb: provides method callc to the failed events.
- _preservation_status.html.erb: adds logic and html to the views to present events.
- config/locales/hyrax.en.yml: inserts headers into localization.
- spec/*: creates tests for the fuctionality.

### CODE REVIEW

**Comment by bwatson78** [comment]
Screen Shot 2020-06-01 at 2 43 56 PM

**Comment by devanshu-m** [comment]
@bwatson78 can you rebase this with master?

**Comment by devanshu-m** [comment]
Since I have worked on this PR with Brad, will it be possible for you to take a look? @wulman16

**Comment by bwatson78** [comment]
@wulman16 Thanks for doing that rebase. Was in my 1:1 with Collin.

**Pull request merged**
