### PR TITLE
Reverts testing to just our customized expectations (#1680).

### PR DESCRIPTION
**Pull request by bwatson78**
spec/presenters/collection_presenter_spec.rb: we originally brought this file in as an overwrite to just test our customizations (described in the top comments). Since we have only altered a small portion of the presenter itself, but the original Rspec assumes a clean install with all Basic Metadata included, the original Rspec really doesn't apply to us.

### CODE REVIEW

**Comment by devanshu-m** [comment]
Are we using behavior from the original collection_type? If we are overwriting that file and using the original behavior, it might be best to keep these tests around. What do you think? @bwatson78

**Comment by bwatson78** [comment]
@devanshu-m It may be worth while, but is it worth our time now? From what I can tell, we have altered/customized the Collection item so much, that the original tests shouldn't apply. I felt like I could take just a day to alleviate all of the original expectations' failures--if we're trying to get green by today, that's not gonna do it.

**Comment by devanshu-m** [comment]
It might be worth the effort. But let's keep this here for now and get everything else green except for this one file. Sound ok? @bwatson78

**Comment by bwatson78** [comment]
Yeah, that's fine

**Pull request closed without merging**
