### PR TITLE
Disable SolrSuggest

### PR DESCRIPTION
**Pull request by devanshu-m**
* SolrSuggest may be responsible for slowdown in ingest pace. Disabling SolrSuggest might help to decrease time taken to create and add a work to a collection. Refer:
https://docs.google.com/presentation/d/1Jj0aC8LhfbcWxe0g8bBhTj1wxKMbkU6v11iJRBKNV3E/edit?copiedFromTrash#slide=id.g44d37b2273_2_0
and
https://docs.google.com/presentation/d/1Jj0aC8LhfbcWxe0g8bBhTj1wxKMbkU6v11iJRBKNV3E/edit?copiedFromTrash#slide=id.g44d37b2273_2_7
and
https://github.com/samvera/active_fedora/pull/1311/files

### CODE REVIEW

**Comment by bess** [comment]
@devanshu-m I 100% endorse this change in solr. However, could you check with @SolomonHD whether making the change to this solr config will actually affect the solr config we're running on the servers? Maybe it will, but I would not assume that without discussing it.

**Comment by SolomonHD** [comment]
This will not affect the solr-cor servers, I believe the solr in this repo only controls the local solr when you run this app in development mode.

**Comment by devanshu-m** [comment]
What do you suggest then? @SolomonHD How do we get these changes on the solr-cor servers?

**Comment by mprefer** [comment]
Changes need to be made to schema.xml and solrconfig.xml that reside in Zookeeper.
They need to be copied from ZK to local disk, modified, then copied back into ZK.

**Comment by SolomonHD** [comment]
Yes this is probably best done manually at this point, the scripts haven't been ran on these boxes in almost a full year. Originally the schema/solrconfig were templated from [here](https://github.com/curationexperts/uclalib_role_solr7/blob/add-solr-cloud/files/hyrax_solr-conf/schema.xml) and [here](https://github.com/curationexperts/uclalib_role_solr7/blob/add-solr-cloud/templates/hyrax_solrconfig/solrconfig_xml.j2) respectively.

**Comment by SolomonHD** [comment]
@devanshu-m Since the /conf folder isn't being used what do you think about deleting it for simplicity?

**Pull request merged**
