### PR TITLE
Corrects the Google Tag script placement.

### PR DESCRIPTION
**Pull request by bwatson78**

### CODE REVIEW

**Comment by rotated8** [comment]
I would have assumed we could use the [Hyrax setup for analytics](https://github.com/samvera/hyrax/wiki/Hyrax-Management-Guide#analytics-and-usage-statistics). Does that not work for us?

**Comment by bwatson78** [comment]
@rotated8 I will attempt the [ENV approach](https://github.com/samvera/hyrax/wiki/Hyrax-Management-Guide#analytics-and-usage-statistics) per our conversation.

**Comment by bwatson78** [comment]
The `ENV` approach 500s when trying to load any dashboard page is all of the necessary Google variables are not set. Trying the `config` approach now.

**Comment by bwatson78** [comment]
The same error occurs when only the config variables are set. Turning on Google Analytics in Hyrax' code means we want to deliver the stats in our own app's UI, no way around that.

**Comment by bwatson78** [comment]
After discussing the full Google Analytics integration requirements, @eporter23 felt it would be better to only do the tagging script and forgo the whole integration. That makes this ticket ready for review.

**Review by alexBLR — APPROVED** [review]

**Pull request merged**
