### PR TITLE
Replaces the depositor of the file with the current_user uid (#1264).

### PR DESCRIPTION
**Pull request by bwatson78**
- app/controllers/hyrax/fixity_checks_controller.rb: includes the current user's `uid` as `initiating_user` argument.
- app/jobs/fixity_check_job.rb: brings in the new `initiating_user` argument and uses it instead of `fixity_file_set.depositor`.
- app/services/hyrax/file_set_fixity_check_service.rb: overrides the hyrax service to accept the new argument.
- lib/tasks/fixity_check.rake: hardcodes the preferred user value into the rake call associated.
- spec/*: inserts the expectation for the `initiating_user` argument.

### CODE REVIEW

**Comment by devanshu-m** [comment]
Instead of making changes to the job, service, and other places, do you think we can just check if a current_user exists and if not (then we assume fixity checking is through the rake task) assign it as Curate System? Only change we would need to do to achieve this would be here: https://github.com/emory-libraries/dlp-curate/pull/1357/files#diff-dfcc26dfd2d5430d81c3ed60468ba9e4R74

**Comment by bwatson78** [comment]
@devanshu-m If you're asking if `current_user` exists in the job or service, it doesn't. Trust me, I tried it with byebug and it's empty. I'll try it again to make sure. Give me a few moments.

**Comment by bwatson78** [comment]
```(byebug) current_user
*** NameError Exception: undefined local variable or method `current_user' for #<Hyrax::FileSetFixityCheckService:0x00007ff7aa8c44d0>

nil
(byebug) session
*** NameError Exception: undefined local variable or method `session' for #<Hyrax::FileSetFixityCheckService:0x00007ff7aa8c44d0>

nil
```

**Comment by bwatson78** [comment]
@devanshu-m I wish it was as easy as that, but `current_user` isn't available past the controller unless you pass it as an argument.

**Comment by devanshu-m** [comment]
Ok, can you copy over specs for the files that are overwritten here from hyrax and make sure tests are passing?

**Comment by bwatson78** [comment]
@devanshu-m RSpec has been imported and updated.

**Pull request merged**
