### PR TITLE
Displays Source alongside Deposit Collection in Is Part Of on Dashboard Works (#1479).

### PR DESCRIPTION
**Pull request by bwatson78**
`app/helpers/hyrax/collections_override_helper.rb`:
> This overrides only one helper method in `Hyrax::CollectionsHelper`, namely `render_collection_links(solr_doc)`. Lines 10 and 11 are the only changes where we are pulling source collections attached to the work, and integrating them into the `collections_list` array that the "Is Part Of:" is fed from.

Note: I couldn't get rspec to load the "Dashboard > All Works" page after associating the work with the deposit collection (e.g. `work.member_of_collections << deposit_collection`). Because of this, I have left with out of the system rspec tests.

### CODE REVIEW

**Comment by bwatson78** [comment]
Screen Shot 2020-09-15 at 1 55 20 PM

**Comment by devanshu-m** [comment]
@bwatson78 Looks good. What's the error with the system test? Can you push the tests to this branch and I can take a look if you want.

**Comment by bwatson78** [comment]
It's actually not technically an error. It's just that, once I build a test scenario and associate the work to the the collection (`work.member_of_collections << deposit_collection`) and then try to visit the `dashboard/works` page, I get the system response saying the page doesn't exist. It exists all the way up to the point that I do the pushing of the deposit collection into `work.member_of_collections`.

**Comment by devanshu-m** [comment]
Have you tried a `work.reload` after `work.save!` and then visiting the page? @bwatson78

**Comment by bwatson78** [comment]
I did try the reload/save on the work as well as all of the collections I created--didn't change the outcome. And I also tried just simulated clicking of the Works and then All Works tab starting from the Dashboard, but still got the page missing html.

**Comment by devanshu-m** [comment]
Makes me wonder if there's a small chance of this error occurring in the ui at some point?

**Comment by bwatson78** [comment]
I'm just not sure it has anything to do with the helper I changed. It's probably just that I'm missing a step building the works.

**Comment by devanshu-m** [comment]
@bwatson78 are you working on making any changes to this?

**Comment by bwatson78** [comment]
I haven't made any changes. Per my last comment, I'm confident that my changes aren't making that error in testing.

**Review by devanshu-m — APPROVED** [review]

**Pull request merged**
